name: Pull Request Checker

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - uses: stellar/stellar-cli@main

      - name: Install make
        run: |
          sudo apt-get install make

      - name: Set Target to wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown

      - name: Test
        run: |
          make all
