name: Pull Request Checker

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Install make
        run: |
          sudo apt-get install make

      - name: Set Target to wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown

      - name: Install Stellar
        run: |
          cargo install --locked stellar-cli

      - name: Test
        run: |
          make all
